---
volumes:
  prometheus-data:
    driver: local
services:
  init_prometheus:
    image: docker.io/prom/prometheus:v2.54.1
    container_name: init_prometheus
    user: root
    entrypoint:
      - /bin/sh
      - -c
      - |
        chown -R 65534:65534 /prometheus
    volumes:
      - ./prometheus-data:/prometheus
  prometheus:
    image: docker.io/prom/prometheus:v2.54.1
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--enable-feature=expand-external-labels"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - ./prometheus-data:/prometheus
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - init_prometheus
