services:
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ${PWD}/docker/data/ollama:/root/.ollama
    tty: true
    restart: unless-stopped

  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    volumes:
      - ${PWD}/docker/data/open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    env_file: .env
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://ollama:11434}
      - WEBUI_SECRET_KEY=${OLLAMA_API_KEY}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
