---
services:
  mongo:
    container_name: mongo
    image: mongo:8.0.9
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db
      - mongo_config:/data/configdb
    restart: unless-stopped
    networks:
      - caddy_network

  mongo-express:
    container_name: mongo-express
    image: mongo-express:1.0.2-20-alpine3.19
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_EXPRESS_URL}
      - ME_CONFIG_BASICAUTH=${MONGO_EXPRESS_BASICAUTH}
    networks:
      - caddy_network

volumes:
  mongo_db:
    name: mongo_db
    driver: local
  mongo_config:
    name: mongo_config
    driver: local

networks:
  caddy_network:
    name: caddy_network
    external: true