---
services:
  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy:v2.11.0
    restart: unless-stopped
    environment:
      NTFY_BASE_URL: ${NTFY_BASE_URL}
      NTFY_CACHE_FILE: ${NTFY_CACHE_FILE}
      NTFY_AUTH_FILE: ${NTFY_AUTH_FILE}
      NTFY_AUTH_DEFAULT_ACCESS: ${NTFY_AUTH_DEFAULT_ACCESS}
      NTFY_BEHIND_PROXY: ${NTFY_BEHIND_PROXY}
      NTFY_ATTACHMENT_CACHE_DIR: ${NTFY_ATTACHMENT_CACHE_DIR}
      NTFY_ENABLE_LOGIN: ${NTFY_ENABLE_LOGIN}
      NTFY_UPSTREAM_BASE_URL: ${NTFY_UPSTREAM_BASE_URL}
      NTFY_WEB_PUSH_PUBLIC_KEY: ${NTFY_WEB_PUSH_PUBLIC_KEY}
      NTFY_WEB_PUSH_PRIVATE_KEY: ${NTFY_WEB_PUSH_PRIVATE_KEY}
      NTFY_WEB_PUSH_FILE: ${NTFY_WEB_PUSH_FILE}
      NTFY_WEB_PUSH_EMAIL_ADDRESS: ${NTFY_WEB_PUSH_EMAIL_ADDRESS}
    volumes:
      - data_ntfy:/var/lib/ntfy
    networks:
      - caddy_network
    ports:
      - 8093:80
    command: serve

volumes:
  data_ntfy:
    name: data_ntfy
    driver: local

networks:
  caddy_network:
    name: caddy_network
    external: true