---
volumes:
  wakapi-data:
    driver: local
services:
  wakapi:
    image: ghcr.io/muety/wakapi:2.11.2
    container_name: wakapi
    ports:
      - 3000:3000
    environment:
      WAKAPI_PASSWORD_SALT: ${WAKAPI_PASSWORD_SALT}
      WAKAPI_EXPOSE_METRICS: true
    volumes:
      - ./wakapi-data:/data
    restart: unless-stopped
