#!/bin/bash

SUPERUSER=code
USER=$1
PASSWORD=$(openssl rand -hex 32)

docker exec -i postgres psql -U ${SUPERUSER} <<EOF
CREATE USER $USER WITH PASSWORD '$PASSWORD';
CREATE DATABASE $USER OWNER $USER;
GRANT ALL PRIVILEGES ON DATABASE $USER TO $USER;
GRANT CONNECT ON DATABASE $USER TO $SUPERUSER;
EOF

docker exec -i postgres psql -U ${SUPERUSER} -d $USER <<EOF
GRANT USAGE ON SCHEMA public TO $SUPERUSER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO $SUPERUSER;
GRANT CREATE ON SCHEMA public TO $SUPERUSER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO $SUPERUSER;
EOF

echo "User $USER created with password: $PASSWORD"