http:
 #region routers
  routers:
    proxmox:
      entryPoints:
        - "https"
      rule: "Host(`proxmox.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: proxmox
    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pihole.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: pihole
    grafana:
      entryPoints:
        - "https"
      rule: "Host(`grafana.local.wywiol.eu`)"
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: grafana

#endregion
#region services
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://192.168.0.200:8006"
        passHostHeader: true
    pihole:
      loadBalancer:
        servers:
          - url: "http://192.168.0.100"
        passHostHeader: true
    grafana:
      loadBalancer:
        servers:
          - url: "http://192.168.0.107:3000"
        passHostHeader: true
#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true
    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipAllowList:
        sourceRange:
        - "192.168.0.0/16"

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers