---
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:2.30.0-alpine
    ports:
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - caddy_network
    restart: unless-stopped

volumes:
  portainer_data:
    name: portainer_data
    driver: local

networks:
  caddy_network:
    name: caddy_network
    external: true