---
services:
  marqo:
    image: marqoai/marqo:latest
    container_name: marqo
    restart: unless-stopped
    networks:
      - frontend
    ports:
      - 8882:8882

networks:
  frontend:
    external: true