x-environment: &default-environment
  DATABASE_URL: ${DATABASE_URL}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  SECRET_KEY: ${SECRET_KEY}
  PORT: ${PORT}
  EMAIL_URL: ${EMAIL_URL}
  GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN}
  DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
  CELERY_WORKER_AUTOSCALE: ${CELERY_WORKER_AUTOSCALE}
  CELERY_WORKER_MAX_TASKS_PER_CHILD: ${CELERY_WORKER_MAX_TASKS_PER_CHILD}
  CSP_DEFAULT_SRC: "self"

x-depends_on: &default-depends_on
  - postgres
  - redis

services:
  postgres:
    image: postgres:16
    environment: *default-environment
    env_file: .env
    restart: unless-stopped
    volumes:
      - postgress-data:/var/lib/postgresql/data
  redis:
    image: redis:7.4
    restart: unless-stopped
  web:
    image: glitchtip/glitchtip:v4.1
    depends_on: *default-depends_on
    ports:
      - "8000:8000"
    environment: *default-environment
    env_file: .env
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
  worker:
    image: glitchtip/glitchtip:v4.1
    command: ./bin/run-celery-with-beat.sh
    depends_on: *default-depends_on
    environment: *default-environment
    env_file: .env
    restart: unless-stopped
    volumes:
      - uploads:/code/uploads
  migrate:
    image: glitchtip/glitchtip:v4.1
    depends_on: *default-depends_on
    command: ./bin/run-migrate.sh
    environment: *default-environment
    env_file: .env

volumes:
  postgress-data:
    driver: local
  uploads:
    driver: local
