---
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - NO_AUTOUPDATE=true
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
