x-glitchtip-environment: &glitchtip-environment
  DATABASE_URL: ${GLITCHTIP_DATABASE_URL}
  SECRET_KEY: ${GLITCHTIP_SECRET_KEY}
  PORT: ${GLITCHTIP_PORT}
  EMAIL_URL: ${GLITCHTIP_EMAIL_URL}
  GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN}
  DEFAULT_FROM_EMAIL: ${GLITCHTIP_DEFAULT_FROM_EMAIL}
  CELERY_WORKER_AUTOSCALE: ${GLITCHTIP_CELERY_WORKER_AUTOSCALE}
  CELERY_WORKER_MAX_TASKS_PER_CHILD: ${GLITCHTIP_CELERY_WORKER_MAX_TASKS_PER_CHILD}
  CSP_DEFAULT_SRC: ${GLITCHTIP_CSP_DEFAULT_SRC}
  REDIS_URL: ${GLITCHTIP_REDIS_URL}

services:
  glitchtip-web:
    container_name: glitchtip-web
    image: glitchtip/glitchtip:v5.1.1
    ports:
      - 8000:8000
    environment: *glitchtip-environment
    volumes:
      - ${PWD}/docker/data/glitchtip/uploads:/code/uploads
    restart: unless-stopped
    networks:
      - caddy_network
      - postgres_network

  glitchtip-worker:
    container_name: glitchtip-worker
    image: glitchtip/glitchtip:v5.1.1
    command: ./bin/run-celery-with-beat.sh
    environment: *glitchtip-environment
    volumes:
      - ${PWD}/docker/data/glitchtip/uploads:/code/uploads
    restart: unless-stopped
    networks:
      - caddy_network
      - postgres_network

  glitchtip-migrate:
    container_name: glitchtip-migrate
    image: glitchtip/glitchtip:v5.1.1
    command: ./bin/run-migrate.sh
    environment: *glitchtip-environment
    networks:
      - caddy_network
      - postgres_network

networks:
  caddy_network:
    name: caddy_network
    external: true
  postgres_network:
    name: postgres_network
    external: true